FROM oaisoftwarealliance/oai-amf:v1.5.1 as amf

# Install dependencies
#install python3.8 
#RUN apt-get update && apt-get install -y python3.8 python3-pip 
ENV DEBIAN_FRONTEND=noninteractive








    


    
