FROM ubuntu:focal

# Install dependencies
#install python3.8 
RUN apt-get update && apt-get install -y python3.8 python3-pip


WORKDIR /openairinterface5g-develop


COPY /openairinterface5g-develop/ /openairinterface5g-develop/

RUN cd cmake_targets/ && \
    ./build_oai -I  --eNB --nrUE --UE --gNB -w USRP
    

    
