#This is to test the amf (Access and Mobility Function) API of the 5G core network

#only dependcies are python3 and mysql
version: "3.3"
services:
  mysql:
    container_name: "mysql"
    image: mysql:latest
    environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=oai_db
    - MYSQL_USER=open5gs
    - MYSQL_PASSWORD=open5gs
    - MYSQL_ROOT=open5gs
    volumes:
      - ./mysql:/var/lib/mysql
      - ./healthscripts/mysql-healthcheck2.sh:/tmp/mysql-healthcheck.sh
    healthcheck:
      test: /bin/bash -c "/tmp/mysql-healthcheck.sh"
      interval: 10s
      timeout: 5s
      retries: 30
    networks:
      public_net:
   # ports:
    #  - "3306:3306"

  amf:
    container_name: "amf"
    image: amf:latest
    expose:
      - 80/tcp
      - 8080/tcp
      - 38412/sctp 
    environment:
            - TZ=America/New_York
            - MCC=208
            - MNC=95
            - REGION_ID=128
            - AMF_SET_ID=1
            - SERVED_GUAMI_MCC_0=208
            - SERVED_GUAMI_MNC_0=95
            - SERVED_GUAMI_REGION_ID_0=128
            - SERVED_GUAMI_AMF_SET_ID_0=1
            - SERVED_GUAMI_MCC_1=460
            - SERVED_GUAMI_MNC_1=11
            - SERVED_GUAMI_REGION_ID_1=10
            - SERVED_GUAMI_AMF_SET_ID_1=1
            - PLMN_SUPPORT_MCC=208
            - PLMN_SUPPORT_MNC=95
            - PLMN_SUPPORT_TAC=0xa000
            # Slice 0 (1, 0xFFFFFF)
            - SST_0=1
            # At least one slice SHALL be defined.
            # All the others are optional
            # Slice 1 (1, 1)
            - SST_1=1
            - SD_1=1
            # Slice 2 (222, 123)
            - SST_2=222
            - SD_2=123
            - AMF_INTERFACE_NAME_FOR_NGAP=eth0
            - AMF_INTERFACE_NAME_FOR_N11=eth0
            # One single SMF instance
            - SMF_INSTANCE_ID_0=1
            - SMF_FQDN_0=oai-smf
         #   - SMF_IPV4_ADDR_0=192.168.70.133
            - SELECTED_0=true
            - NF_REGISTRATION=no
            - USE_FQDN_DNS=yes
            - SMF_SELECTION=yes
            - EXTERNAL_AUSF=no
            - EXTERNAL_UDM=no
            - EXTERNAL_NSSF=no
           # - NRF_IPV4_ADDRESS=192.168.70.130
         #   - NRF_FQDN=oai-nrf
           # - AUSF_IPV4_ADDRESS=192.168.70.138
        #    - AUSF_FQDN=oai-ausf
       #     - UDM_IPV4_ADDRESS=192.168.70.137
            - UDM_FQDN=oai-udm
            # changes for HTTP2
            - USE_HTTP2=yes
          #  - NRF_PORT=8080
           # - AUSF_PORT=8080
          #  - UDM_PORT=8080
    networks:
       public_net:
    depends_on:
      - mysql

networks:
  public_net:
  


   
